version: "3"
services:
  server_app:
    build:
      context: ./server-app
      args:
        - BINARY_PATH_APP=/server_binaries/app
    networks:
      - internal-network
      - external-network
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ${BINARY_PATH_APP:?path to rust binaries must be set}:/server_binaries/app
    restart: always

networks:
  internal-network:
    driver: bridge
    internal: true
  external-network:
    driver: bridge
